### ISSUE TITLE
Missing forth.ark.h

### ISSUE THREAD

**Issue by seanohalpin** [jinhanada/elfort#1]
Following the README, after issuing:

`$ make meta`

I get the error:

`src/arkam_console.c:2:10: fatal error: 'forth.ark.h' file not found`

It appears there is a circular dependency: arkam depends on out/forth.ark.h which depends on arkam.

**Comment by jinhanada** [comment]
Thanks!
Updated instruction in README.md of [Arkam](https://github.com/jinhanada/arkam).
out/forth.ark.h actually depends on arkvm and forth.ark.
That error may come from missing `out` or `bin` directory.
`make all` should be run before `make meta`.
